### ISSUE TITLE
Screen edge panning is linked to physical screen; not the viewport

### ISSUE THREAD

**Issue by joekaiser** [Merlin1846/Panning-Camera-Plugin#1]
Great add-on and saved me a ton of time. One thing I noticed is that the screen edge panning is triggered by the edge of my monitor and not the viewport. I'd expect it to work based on that instead. Is the current behavior your intention?

**Comment by Merlin1846** [comment]
It should be based on the windows size. I'll take a look at it though.

**Comment by joekaiser** [comment]
Here are the display settings I'm using. I'm running 4.1.3

and here is a simple project to reproduce it
[PanCamTest.zip](https://github.com/Merlin1846/Panning-Camera-Plugin/files/13402394/PanCamTest.zip)



![image](https://github.com/Merlin1846/Panning-Camera-Plugin/assets/1521110/79c60ba4-1169-4d9d-bb43-a69a561290f2)

**Comment by Merlin1846** [comment]
I figured out the issue. So the `get_size()` method doesn't work properly when you have stretch mode set to viewport. This is because the window is essentially always the size of the screen but then scaled down.

Another thing, like any other addon you should place it inside the addons folder instead of moving it somewhere else. You also deleted the license among other things from the addon which in this case is the MIT license. You should leave the file in its place with the addon and simply have something in the credits that shows the license for the addon. No the license does not cover or affect your project, only the addon, so you don't have to worry about that. Not sure if you only did this when making the example or not.

I will see if I can make it work with the stretch mode set to viewport, however this is rarely what many Godot users actually want when they set that setting so I'd recommend you read through this. [https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html)

If you need help with getting the UI to scale with the viewport just tell me and I can help.
